import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 10, fontFamily: "Helvetica", color: "#1e293b" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
  agencyName: { fontSize: 16, fontWeight: 700, color: "#4338ca" },
  docTitle: { fontSize: 20, fontWeight: 700 },
  section: { marginBottom: 16 },
  label: { fontSize: 8, fontWeight: 700, color: "#64748b" },
  value: { fontSize: 10, marginBottom: 8 },
  table: { borderTopWidth: 1, borderTopColor: "#e2e8f0", paddingTop: 8, marginTop: 8 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 4 },
  rowLabel: { fontSize: 10, color: "#475569" },
  rowValue: { fontSize: 10, fontWeight: 700 },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 8,
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#1e293b",
  },
  footer: { marginTop: 30, fontSize: 8, color: "#94a3b8", textAlign: "center" },
});

export type InvoicePdfData = {
  agencyName: string;
  agencyAddress?: string | null;
  invoiceNumber: string;
  issuedAt: string;
  customerName: string;
  customerPhone: string;
  destination: string;
  startDate: string;
  endDate: string;
  packageAmount: number;
  collected: number;
  balance: number;
};

function formatDate(value: string) {
  return new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
}

function formatCurrency(value: number) {
  return `Rs. ${value.toLocaleString("en-IN")}`;
}

function InvoiceDocument({ data }: { data: InvoicePdfData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.agencyName}>{data.agencyName}</Text>
            {data.agencyAddress && <Text style={styles.value}>{data.agencyAddress}</Text>}
          </View>
          <View>
            <Text style={styles.docTitle}>INVOICE</Text>
            <Text style={styles.value}>{data.invoiceNumber}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Billed to</Text>
          <Text style={styles.value}>{data.customerName}</Text>
          <Text style={styles.value}>{data.customerPhone}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Trip</Text>
          <Text style={styles.value}>
            {data.destination} · {formatDate(data.startDate)} - {formatDate(data.endDate)}
          </Text>
          <Text style={styles.label}>Issued</Text>
          <Text style={styles.value}>{formatDate(data.issuedAt)}</Text>
        </View>

        <View style={styles.table}>
          <View style={styles.row}>
            <Text style={styles.rowLabel}>Travel package — {data.destination}</Text>
            <Text style={styles.rowValue}>{formatCurrency(data.packageAmount)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.rowLabel}>Amount collected</Text>
            <Text style={styles.rowValue}>-{formatCurrency(data.collected)}</Text>
          </View>
          <View style={styles.totalRow}>
            <Text style={styles.rowLabel}>Balance due</Text>
            <Text style={styles.rowValue}>{formatCurrency(Math.max(data.balance, 0))}</Text>
          </View>
        </View>

        <Text style={styles.footer}>Generated by {data.agencyName} via TrailPilot</Text>
      </Page>
    </Document>
  );
}

export async function renderInvoicePdf(data: InvoicePdfData): Promise<Buffer> {
  return renderToBuffer(<InvoiceDocument data={data} />);
}
