import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 10, fontFamily: "Helvetica", color: "#1e293b" },
  agencyName: { fontSize: 16, fontWeight: 700, color: "#4338ca" },
  docTitle: { fontSize: 18, fontWeight: 700, marginTop: 16, marginBottom: 16 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: "#e2e8f0" },
  label: { fontSize: 9, color: "#64748b" },
  value: { fontSize: 10, fontWeight: 700 },
  amountBox: { marginTop: 20, padding: 16, backgroundColor: "#f8fafc", borderRadius: 4 },
  amountLabel: { fontSize: 9, color: "#64748b" },
  amount: { fontSize: 22, fontWeight: 700, color: "#4338ca" },
  footer: { marginTop: 30, fontSize: 8, color: "#94a3b8", textAlign: "center" },
});

export type ReceiptPdfData = {
  agencyName: string;
  receiptNumber: string;
  paidAt: string;
  customerName: string;
  destination: string;
  amount: number;
  method: string;
  reference?: string | null;
};

function formatDate(value: string) {
  return new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
}

function ReceiptDocument({ data }: { data: ReceiptPdfData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.agencyName}>{data.agencyName}</Text>
        <Text style={styles.docTitle}>Payment Receipt</Text>

        <View style={styles.row}>
          <Text style={styles.label}>Receipt number</Text>
          <Text style={styles.value}>{data.receiptNumber}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Date</Text>
          <Text style={styles.value}>{formatDate(data.paidAt)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Received from</Text>
          <Text style={styles.value}>{data.customerName}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Trip</Text>
          <Text style={styles.value}>{data.destination}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Payment method</Text>
          <Text style={styles.value}>{data.method}</Text>
        </View>
        {data.reference && (
          <View style={styles.row}>
            <Text style={styles.label}>Reference</Text>
            <Text style={styles.value}>{data.reference}</Text>
          </View>
        )}

        <View style={styles.amountBox}>
          <Text style={styles.amountLabel}>Amount received</Text>
          <Text style={styles.amount}>Rs. {data.amount.toLocaleString("en-IN")}</Text>
        </View>

        <Text style={styles.footer}>Generated by {data.agencyName} via TrailPilot</Text>
      </Page>
    </Document>
  );
}

export async function renderReceiptPdf(data: ReceiptPdfData): Promise<Buffer> {
  return renderToBuffer(<ReceiptDocument data={data} />);
}
